
SELECT COUNT (DISTINCT SABOR) 
FROM TABELA_DE_PRODUTOS;

SELECT TOP 10 * 
FROM NOTAS_FISCAIS 
WHERE DATA_VENDA = '2017-10-01';

SELECT CODIGO_DO_PRODUTO 
FROM TABELA_DE_PRODUTOS 
WHERE NOME_DO_PRODUTO = 'Linha Refrescante - 1 Litro - Morango/Limao';

SELECT COUNT(*) AS QUANTIDADE 
FROM ITENS_NOTAS_FISCAIS 
 WHERE CODIGO_DO_PRODUTO = '1101035' AND QUANTIDADE = 99;

SELECT CODIGO_DO_PRODUTO, SUM(QUANTIDADE) VENDAS_TOTAIS 
FROM ITENS_NOTAS_FISCAIS 
GROUP BY CODIGO_DO_PRODUTO 
ORDER BY VENDAS_TOTAIS DESC;

SELECT CODIGO_DO_PRODUTO, SUM(QUANTIDADE) VENDAS_TOTAIS 
FROM ITENS_NOTAS_FISCAIS 
GROUP BY CODIGO_DO_PRODUTO 
	HAVING SUM(QUANTIDADE) > 394000 
ORDER BY VENDAS_TOTAIS DESC;

SELECT NOME, 
(CASE WHEN LIMITE_DE_CREDITO >= 150000  THEN 'GRANDES'
WHEN LIMITE_DE_CREDITO BETWEEN 110000 AND 150000 THEN 'MÉDIO'
ELSE 'PEQUENO' END) AS LIMITE_MENSAL 
FROM TABELA_DE_CLIENTES

